### ISSUE TITLE
To fix: Design & quiescent draw

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/Buck_Regulator_AP63203#2]
Hi folks,

I finally got around to testing the quiescent draw of the BabyBuck version of the AP63203 and I'm afraid the results aren't good.

As you can see in the table below, Iq ranges from 133-185 uA (no load), which is considerably greater than the 22 uA listed in the datasheet. While there is certainly some overhead to be expected (comparable Pololu regulators sit at about 50-60 uA with no load), 130-185 uA is certainly getting up there.

However, my main concern is regarding Iq when the regulator is disabled. The AP63203 has a shutdown current supply of 1 uA. However, as shown in the table, Iq scales proportionally with VIN when disabled. This looks to simply be due to the 100kΩ resistor tied to EN and is frankly quite a bummer.

VIN (V) | EN | Iq (uA)
-- | -- | --
5 | HIGH | 133
12 | HIGH | 133
24 | HIGH | 185
5 | LOW | 51
12 | LOW | 122
24 | LOW | 240

From the datasheet, we can see the recommended design when making use of the EN pin:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/22924092/217391849-e45ee528-9124-47a2-ac49-d73683d94dd2.png">

I actually measured VON and VOFF for my particular unit to be 1.19V and 1.10V, respectively. Based on my calculations, I get an R5 = 18.5 kΩ and R6 = 200 kΩ. I'm not sure where 100kΩ/100kΩ came from, but I'd been keen to learn more.

I've been advised that a hardware revision is unlikely anytime soon, but it would still be good to get this info out there.

Happy for any feedback or corrections to my math and/or assumptions.

Cheers,
Adam

P.S. In response to the other open GitHub issue, the inductor should indeed be 3.9 uH for the AP63203, not 4.7 uH. I don't know enough about inductors to know if this makes a difference, though!

**Comment by adamgarbo** [comment]
After spending more time reading the datasheet, I'm wondering did the BabyBuck even need the resistive divider on EN?

<img width="711" alt="image" src="https://user-images.githubusercontent.com/22924092/217405344-55d9a695-2166-4825-bc0a-417495f590f4.png">

**Comment by SFE-Brudnerd** [comment]
Hi @adamgarbo, while I can't comment specifically why the original designer chose the 100k top/bottom for the divider, I'd like to hazard a guess that the thinking was if the user wanted to directly connect the enable pin to a microcontroller GPIO that the low cutoff would be at 1.65V. The datasheet doesn't really make it clear which voltage it's talking about in the R5/R6 calculations, however based on other parts from the same manufacturer that do specify which voltage, they're talking about the VIN voltage, not the voltage seen at the enable pin. Not saying this was the correct choice, but seems like it was the choice made.

That said, using Eq 6 and solving for Voff using R5/R6=100k, I get a Voff of 1.65V, which is the center of a 3.3V GPIO. Von then becomes ~2.1V (2.089 V) when solving Eq 5 for Von. This tells me that it seems it might have been a misinterpretation of the datasheet as 1.65V seems like a good number being half of 3.3V. With VIN=1.65V, the EN pin would see 0.825V, which through the 20k resistor would draw ~41.25uA. Coupled with the ~5.5uA gets you quite close to the values you measured. Since you measure with 5V, it will likely be a bit higher. Keep in mind that this is without considering the ~2% error just from the 2 1% resistors alone. There could be parasitics elsewhere.

To your comment about the inductor, using a higher valued inductor will shift the center notch of the impedance graph, essentially increasing the resistance on your output line. Using the datasheet's 1.1MHz f_sw, a 3.9uH inductor will impart ~26.95 ohms, whereas 4.7uH will impart ~32.48 ohms. Also keep in mind these are 20% parts, so those values are ideal. The unfortunate answer is that there will be a bit more parasitic loss in your device.

Are you able to describe or provide a schematic of your current measurement setup? I'd like to understand the instrumentation you're using to achieve your results and see if I can provide some further suggestions or for things we can do in the future for ultra-low power edge cases such as these.

**Comment by SFE-Brudnerd** [comment]
As a suggestion for how to mitigate things, I suggest outright removing R5/R6 if possible. That should help reduce the shutdown losses.

**Comment by adamgarbo** [comment]
Thanks for the detailed response, @SFE-Brudnerd.

Just a quick note that I also was scratching my head about VON and VOFF until I actually connected EN to my Siglent power supply and measured when the regulator output turned on and off. It turns out the values correspond to VEN_H and VEN_L in the datasheet:

![image](https://user-images.githubusercontent.com/22924092/217878830-9927d4cd-f0dc-4b1c-9a85-24ee88859608.png)

Happy to provide more info about my test setup later on!

Cheers,
Adam

**Comment by adamgarbo** [comment]
I also agree that R5/R6 could be removed as they seem to be redundant for this particular application, where if EN is left open, the regulator will automatically startup, and it can be controlled with 3.3V logic otherwise.

**Comment by adamgarbo** [comment]
In response to your earlier inquiry, @SFE-Brudnerd, for the AP63203-based BabyBuck, I connected a programmable DC power supply to the EN pin and a 12V to VIN. Using a PicoScope oscilloscope, I observed the voltages on the EN and VOUT pins. I then adjusted the voltage on the EN pin in 0.01 V steps until I observed the regulator turning on (VON) and off (VOFF). These voltages were 1.19 V and 1.10 V, respectively.

<img width="1944" alt="Screenshot 2023-02-13 at 12 23 03 PM" src="https://user-images.githubusercontent.com/22924092/218528158-62a6b976-2fc5-4d7b-9c77-52cee6548917.png">

**Comment by adamgarbo** [comment]
Hi @SFE-Brudnerd 

I removed R1 and R2 on the 3.3V BabyBuck with a hot-air rework station and the resulting quiescent currents are as follows:

**EN Enabled:**

| VIN (V) 	| Iq (uA) 	|
|:-------:	|:-------:	|
|    5    	|   102   	|
|    12   	|    71   	|
|    24   	|    64   	|

**EN Disabled:**
| VIN (V) 	| Iq (uA) 	|
|:-------:	|:-------:	|
|    5    	|   0.22  	|
|    12   	|   0.68  	|
|    24   	|   1.1   	|

These are **_exactly_** the kind of quiescent draws I was hoping for.

With R1 and R2 removed, I also tested the UVLO. VIN rising to turn on the regulator output was at 3.49V (agrees with datasheet) and the VIN falling (UVLO) to turn off the regulator output was 3.15 V. I apologize earlier I was mixing up the logic VEN_H and VEN_L with the UVLO. I now have a better understanding of what the UVLO is.

Now that I've removed R1 and R2, I realize I can't measure the modified UVLO. What did the 100k/100k voltage divider end up changing them to?

Cheers,
Adam

**Comment by SFE-Brudnerd** [comment]
Glad you're getting the results you were hoping for! As for measuring UVLO without those, try measuring the output while slowly decreasing the input voltage. When the output shuts off, the VIN voltage is your Voff. Slowly increase your input voltage until it turns back on and you'll have your Von. It should match pretty closely to the datasheet, snipped below.

![image](https://user-images.githubusercontent.com/101155592/218839889-0ae99fdc-b37e-402a-9a72-aee3e1afae45.png)

Unfortunately, since there was a misunderstanding of the math being done in the original design, the UVLO with the original 100k/100k is well below the built-in UVLO. I calculated it above to be Voff = 1.65V and Von = 2.1V.

**Comment by adamgarbo** [comment]
Hi @SFE-Brudnerd,

I appreciate you taking the time to help with this issue. It's unfortunate that the 3.3V BabyBuck ended up having a completely redundant UVLO voltage divider. What would you have preferred the actual ULVO value to be?

The good news is the quiescent draws I hoped for with the BabyBucks are possible. The bad news is that removing R1 and R2 won't be a feasible solution. While I'd be comfortable making modifications to SMD components, many of the users who are building their own versions of my projects wouldn't be. 

Unfortunately, it looks like I'm stuck using Pololu regulators for the foreseeable future. Bryan was clear a hardware revision is a low priority. Considering I was the one to suggest the 5V version of the BabyBuck, I should have made more of an effort to ask to review the design before it went for production.

Cheers,
Adam

**Comment by SFE-Brudnerd** [comment]
I think the question of "What would you have preferred?" is answered with a generic answer of "it depends on your application". I think the biggest consideration would be making sure that it shutdown before pulling a battery lower than it's recommended voltage to avoid damage. Beyond that, I think it comes down to a lot of the considerations I mentioned in the other thread.

**Comment by adamgarbo** [comment]
Hi @SFE-Brudnerd,

To quickly clarify, you mentioned there was a misunderstanding with the math that resulted in incorrect resistor values for the voltage divider on the BabyBuck. To rephrase my question, what are the correct resistor values (for this particular SparkFun application)?

Edit: For the AP63203, I measured the default Von = 3.5V and Voff = 3.15V without R1 & R2. I've also watched the 3.3V Vout degrade as Vin is decreased towards the UVLO. So, if I understand correctly, these are the "functional" and "undefined" regions in the TI figure you wish to avoid. I'm assuming the goal is to raise the UVLO to avoid these problem areas completely. The tradeoff appears to be between power efficiency and an optimal UVLO.

The question is (for SparkFun) is a default Von = 3.5V and UVLO = 3.08V really all that bad? You're currently selling a product with Voff = 1.65V and Von = 2.1V, so in a way, it's a moot point.  The main point here is that users who are going to be purchasing and using these BabyBuck regulators are doing so because they need to work with voltages outside the supported range of the ubiquitous AP2112 and AP7361C regulators. However, power efficiency is still important. For my own projects, the default Von/Voff/UVLO values are completely sufficient, and I suspect this would be the case for many other users. If the voltage of my 12V battery gets to be anywhere near 3V, I have **_much_** bigger problems to worry about.

Thanks for listening! 

Cheers,
Adam

**Comment by SFE-Brudnerd** [comment]
Hi @adamgarbo, 

I think you answered your own question towards the bottom. Yes, the 100k/100k combo providing a lower Von/Voff is a moot point. In this application it doesn't make sense since it won't ever hit that without first hitting the default value. 

For our particular use case (selling a hopefully generic product to fit the widest audience), having any resistors to modify the UVLO fits that bill. I can't comment on the decisions my predecessors made for the values as I wasn't with the company at the time, nor is that engineer still with the company for me to ask them.

To answer your question of is the default really all that bad, it's not. I may have done something differently had I been the designer of that product. However, leaving an enable in an undefined state (open) isn't the best for people who just want to buy the product and have it work the second they plug it in. They would have to drive the enable high, which some users might not know to do, potentially causing unwanted/unwarranted backlash. In our case of trying to meet the broadest audience, we should be providing that pull up enable and the ability to modify the UVLO for their purposes. If we didn't include those pads at all, we would reduce the set of potential use cases for the product.

Your point about having a 12V battery go near 3V is exactly the kind of situation where a user would want to modify the UVLO. The user won't want that as it means the user is damaging their battery and they should have shut down their regulator sooner. I think in your case with your power requirements, while we try to provide at least an 80% use case coverage solution with our products, you might be an outlier in this case. Thankfully, you have an easy enough solution, though it might not be as straight forward for everyone.

**Comment by adamgarbo** [comment]
Thanks, @SFE-Brudnerd,

I appreciate you taking the time to respond. I do understand the case for releasing a product that can be used by the widest audience. This is a conversation I've had many times in the past with other SparkFun folks and I am well aware that my use cases are oftentimes an extreme outlier. I have a long history of ~~complaining~~ offering constructive criticism regarding power efficiency to both SparkFun and Adafruit. This is in hopes that it will be taken into consideration in future designs. In my opinion, power efficiency and versatile designs that suit a wide audience don't have to be mutually exclusive. The products that Paul Clark's designs are a perfect example of this (sorry Paul! :wink:).

In the case of the AP63203/AP63357, perhaps the best/easiest solution would be to simply have a jumper pad where the end-user could slice the trace to disable R1/R2 instead of having to remove them with a hot-air rework station.

As a side note, EN can be left floating for automatic startup on the AP63203/AP63357:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/22924092/219087368-d1971f42-7cfe-438f-a881-5c5c8b90af4c.png">

Cheers,
Adam

**Comment by SFE-Brudnerd** [comment]
I'll certainly take that into consideration in the future for power products. I come from a power electronics background and enjoy those kinds of projects. I completely agree about that. In the case of the AP63357, our biggest concerns were space constraints and thermal conduction. You can't get the performance you want if you can't get the heat out in such a small board. 

Good to know about the EN pin, I'll admit I must have missed that last bullet point.

**Comment by adamgarbo** [comment]
@SFE-Brudnerd can you re-open this issue as a reminder that future production runs should address the R1/R2 issue? 

Ideally, the R1/R2 SMD resistors could be removed from the BOM but the pads could stay for user customization. A benefit being the product wouldn't require a hardware revision.
